# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build tf2autobot`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t tf2autobot`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000
ENV DOCKER=true

WORKDIR /app

RUN addgroup --system tf2autobot && \
          adduser --system -G tf2autobot tf2autobot

COPY dist/ tf2autobot/
RUN chown -R tf2autobot:tf2autobot .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix tf2autobot --omit=dev -f install

CMD [ "node", "tf2autobot/main" ]
